### PR TITLE
Fix sort in C++ and remove unnecessary copies

### PR DESCRIPTION
**Pull request by elliotgoodrich**
Revert the sort back to descending by occurrence. 

The type of `p` on line 21 is `std::pair<const std::string, int>` so the call
to `move` on the next line will return `const std::string&` instead of an
r-value reference. This means that there is still an additional string copy
here. This commit stores pointers to the string to avoid this extra copy.

A new `struct` called `word_freq` has been created because it is a POD type
(unlike `std::pair<const std::string*, int>`). We replace the `std::vector`
with a dynamically allocated array to avoid calling the destructor of any
`word_freq` objects. Also creating the array with the correct size avoids
any reallocation and branching in `push_back`.

### CODE REVIEW

**Comment by juditacs** [comment]
Please fix the memory leak.

**Comment by elliotgoodrich** [comment]
What tool are you using to detect the leak?

**Comment by juditacs** [comment]
Oh, sorry, I didn't realize it was a unqiue_ptr. You can use make_unique btw, clang 3.6 supports c++14.

**Comment by juditacs** [comment]
vector::reserve does not call the default constructors, wouldn't that work instead of the unique_ptr?

**Comment by juditacs** [comment]
What compiler and what version are you using? I get compilation errors with both gcc and clang. Granted, this gcc version does not support c++14, so no polymorphic lambda.

**Comment by elliotgoodrich** [comment]
It could do, but using `std::unique_ptr` guarantees that the dtor of `word_freq` isn't called. I'm sure some (all?) compilers can optimise the dtor of the `vector` to just release memory, but this isn't guaranteed.

If you like I can change this PR to just fix the sort and store `std::string*` instead of copies and not change `vector` to `unique_ptr`? I don't think it will have much affect on the speed (I'm sure most of the best optimisations now are replacing the streams with something faster).

**Comment by elliotgoodrich** [comment]
Compiles with gcc >=4.9.0 and Clang >=3.5.0 (both require `-std=c++14` compile flag)
